// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkgrrvWDzzTRR_Dj022B-C8Te607qROz8',
    appId: '1:56125949298:web:db553122c58fca821349eb',
    messagingSenderId: '56125949298',
    projectId: 'biletvarbilet-307ac',
    authDomain: 'biletvarbilet-307ac.firebaseapp.com',
    storageBucket: 'biletvarbilet-307ac.firebasestorage.app',
    measurementId: 'G-VT9W09093Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKV4j8ve3d8GHE-RoxWJDfB-hR2trH5Lg',
    appId: '1:56125949298:android:99323ede9f04c30d1349eb',
    messagingSenderId: '56125949298',
    projectId: 'biletvarbilet-307ac',
    storageBucket: 'biletvarbilet-307ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_tZknBca7HlnzU0anjQQ7xbXgp2FpAD8',
    appId: '1:56125949298:ios:9949d6f0058d24401349eb',
    messagingSenderId: '56125949298',
    projectId: 'biletvarbilet-307ac',
    storageBucket: 'biletvarbilet-307ac.firebasestorage.app',
    iosBundleId: 'com.kplus.biletvarbilet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_tZknBca7HlnzU0anjQQ7xbXgp2FpAD8',
    appId: '1:56125949298:ios:a0438bbccb82ff711349eb',
    messagingSenderId: '56125949298',
    projectId: 'biletvarbilet-307ac',
    storageBucket: 'biletvarbilet-307ac.firebasestorage.app',
    iosBundleId: 'com.example.bamobile1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkgrrvWDzzTRR_Dj022B-C8Te607qROz8',
    appId: '1:56125949298:web:80946538425ee9431349eb',
    messagingSenderId: '56125949298',
    projectId: 'biletvarbilet-307ac',
    authDomain: 'biletvarbilet-307ac.firebaseapp.com',
    storageBucket: 'biletvarbilet-307ac.firebasestorage.app',
    measurementId: 'G-673LLZ1FZ7',
  );

}